name: Deploy to dockerhub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: Setup ssh key 
#      uses: webfactory/ssh-agent@v0.5.4
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: setup SSH key
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
      shell: bash
      env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

    - name: test ssh
      run: |
        ssh root@matb.it hostname

    - name: get version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build, tag, and push image to dockerhub
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo version ${{ steps.vars.outputs.tag }} 
        echo docker build
        docker build . -t paolini/matbit
        docker tag paolini/matbit paolini/matbit:${{ steps.vars.outputs.tag }}
        echo docker push
        docker login -u paolini -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push paolini/matbit
        docker push paolini/matbit:${{ steps.vars.outputs.tag }}
        ssh root@matb.it docker-compose -f docker/matbit/docker-compose.yml pull
        ssh root@matb.it docker-compose -f docker/matbit/docker-compose.yml up -d
