name: Deploy to dockerhub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup ssh key 
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Get version from package.json
      id: vars
      run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: paolini
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      run: |
        set -e
        echo version ${{ steps.vars.outputs.version }}
        docker build . -t paolini/matbit
        docker tag paolini/matbit paolini/matbit:${{ steps.vars.outputs.version }}
        docker push paolini/matbit
        docker push paolini/matbit:${{ steps.vars.outputs.version }}
#        ssh -o "StrictHostKeyChecking no" root@matb.it docker-compose -f docker/matbit/docker-compose.yml pull
#        ssh -o "StrictHostKeyChecking no" root@matb.it docker-compose -f docker/matbit/docker-compose.yml up -d
